#!/usr/bin/env python3
"""Convert the iOS template icons (apps/ios/MagicMobile/Assets.xcassets/*.svg) into Android
VectorDrawables. iOS draws these with .renderingMode(.template): only the shape (alpha)
matters and the view supplies the colour, so every visible shape becomes one opaque white
fill that Compose tints. Supports the subset the icons use: path, rect, circle, g, and
fill="none"/class fills. Anything else fails loudly instead of drawing a wrong icon.

Usage: svg_to_vector.py OUTPUT_DIR SVG...
"""
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

SVG = "{http://www.w3.org/2000/svg}"


def number(value, default=0.0):
    if value is None:
        return default
    return float(re.sub(r"[a-z%]+$", "", value.strip()))


def hidden(element, class_fills):
    fill = element.get("fill")
    style = element.get("style", "")
    if fill == "none" or "fill:none" in style.replace(" ", ""):
        return True
    for name in element.get("class", "").split():
        if class_fills.get(name) == "none":
            return True
    return False


def shape_path(element):
    tag = element.tag.replace(SVG, "")
    if tag == "path":
        return element.get("d")
    if tag == "rect":
        x, y = number(element.get("x")), number(element.get("y"))
        w, h = number(element.get("width")), number(element.get("height"))
        return f"M{x},{y}h{w}v{h}h{-w}Z"
    if tag == "circle":
        cx, cy, r = number(element.get("cx")), number(element.get("cy")), number(element.get("r"))
        return f"M{cx - r},{cy}a{r},{r} 0 1,0 {2 * r},0a{r},{r} 0 1,0 {-2 * r},0Z"
    if tag == "polygon":
        points = re.findall(r"-?[0-9.]+(?:e-?\d+)?", element.get("points", ""))
        pairs = [f"{points[i]},{points[i + 1]}" for i in range(0, len(points) - 1, 2)]
        return "M" + "L".join(pairs) + "Z" if pairs else None
    raise ValueError(f"unsupported SVG element <{tag}>")


def convert(svg_path: Path) -> str:
    root = ET.parse(svg_path).getroot()
    viewbox = [number(v) for v in root.get("viewBox", "").replace(",", " ").split()]
    if len(viewbox) != 4:
        raise ValueError(f"{svg_path}: missing viewBox")
    if any(v != 0 for v in viewbox[:2]):
        raise ValueError(f"{svg_path}: viewBox origin must be 0,0")
    class_fills = {}
    for style in root.iter(SVG + "style"):
        for name, body in re.findall(r"\.([\w-]+)\s*\{([^}]*)\}", style.text or ""):
            match = re.search(r"fill:\s*([^;]+)", body)
            if match:
                class_fills[name] = match.group(1).strip()
    paths = []
    for element in root.iter():
        tag = element.tag.replace(SVG, "")
        if tag in ("svg", "g", "style", "title", "desc", "defs", "metadata"):
            if tag == "g" and element.get("transform"):
                raise ValueError(f"{svg_path}: group transforms are not supported")
            continue
        if element.get("transform"):
            raise ValueError(f"{svg_path}: shape transforms are not supported")
        if hidden(element, class_fills):
            continue
        data = shape_path(element)
        if not data:
            continue
        rule = element.get("fill-rule") or element.get("clip-rule")
        fill_type = '\n        android:fillType="evenOdd"' if rule == "evenodd" else ""
        compact = " ".join(data.split())
        paths.append(f'    <path\n        android:fillColor="#FFFFFFFF"{fill_type}\n        android:pathData="{compact}"/>')
    if not paths:
        raise ValueError(f"{svg_path}: no visible shapes")
    width, height = viewbox[2], viewbox[3]
    scale = 24 / max(width, height)
    return ("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n"
            f"<!-- Generated by scripts/android/svg_to_vector.py from the iOS {svg_path.name}; regenerate if it changes. -->\n"
            "<vector xmlns:android=\"http://schemas.android.com/apk/res/android\"\n"
            f"    android:width=\"{round(width * scale, 2)}dp\"\n    android:height=\"{round(height * scale, 2)}dp\"\n"
            f"    android:viewportWidth=\"{width:g}\"\n    android:viewportHeight=\"{height:g}\">\n"
            + "\n".join(paths) + "\n</vector>\n")


def main():
    out = Path(sys.argv[1])
    out.mkdir(parents=True, exist_ok=True)
    for name in sys.argv[2:]:
        source = Path(name)
        target = out / (source.stem.replace("-", "_").lower() + ".xml")
        target.write_text(convert(source))
        print(f"{source.name} -> {target.name}")


if __name__ == "__main__":
    main()
