URL=https://github.com/ineedsomesleep5/MagicMobile/releases/download/server-trial-build5-7d39dbf/render-build5-7d39dbf.tar.gz
SHA256=77e3d0f7454837c23487ea5b60a1987ac4088024f8308fae0febce8c6f8a5b9c
DIRECTORY=runtime-build5-7d39dbf
