#!/usr/bin/env python3
"""Generate the engine build identity that save/resume checkpoints must match.

A checkpoint is Java-serialized engine state, so it is only readable by a build with the
same adapter source, upstream pin and reviewed upstream patches. The digest covers those
inputs; the card catalogue has its own hash. This is not a release or native identity.
"""
from __future__ import annotations
import argparse, hashlib
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
TREES=('engine/core/src/main/java','engine/xmage/src/main/java','platform/java')
FILES=('upstream.lock.json','scripts/prepare_upstream.py','scripts/prepare_mobile_repository.py')

def identity(root: Path=ROOT) -> str:
    paths=[p for tree in TREES for p in (root/tree).rglob('*') if p.is_file()]
    paths+=[root/name for name in FILES]
    value=hashlib.sha256()
    for path in sorted(paths,key=lambda p:p.relative_to(root).as_posix()):
        data=path.read_bytes()
        value.update(path.relative_to(root).as_posix().encode()+b'\0'+str(len(data)).encode()+b'\0'+data)
    return 'sha256:'+value.hexdigest()

def main() -> None:
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output',type=Path,required=True,help='generated Java source root')
    args=parser.parse_args()
    target=args.output/'io/magicmobile/generated/EngineBuildIdentity.java'
    target.parent.mkdir(parents=True,exist_ok=True)
    value=identity()
    target.write_text('package io.magicmobile.generated;\n\n'
        '/** Generated by scripts/engine_build_identity.py. Save/resume checkpoints must match it. */\n'
        'public final class EngineBuildIdentity {\n'
        f'    public static final String VALUE="{value}";\n'
        '    private EngineBuildIdentity() {}\n}\n')
    print('Engine build identity',value)

if __name__=='__main__':main()
