#!/usr/bin/env python3
"""Trace design/brand/icon-master-2026-09-23.png into SwiftUI paths (BrandMarkPaths.swift).

Needs Pillow + numpy and `potrace` (brew install potrace). Colors are separated by hue so
anti-aliased edges never leak between the cream M and the coral card frame.
Usage: trace_logo.py MASTER.png OUT.swift
"""
import re
import subprocess
import sys
import tempfile
import os

import numpy as np
from PIL import Image


def masks(path):
    im = np.asarray(Image.open(path).convert("RGB")).astype(float)
    r, g, b = im[:, :, 0], im[:, :, 1], im[:, :, 2]
    coral = np.clip((r - g - 2) / 150, 0, 1)
    cream = np.clip((np.minimum(np.minimum(r, g), b) - 32) / (236 - 32), 0, 1) * (1 - coral)
    return im.shape[1], {"coral": coral, "cream": cream}


def trace(coverage, tmp):
    pgm = os.path.join(tmp, "m.pgm")
    svg = os.path.join(tmp, "m.svg")
    Image.fromarray(((1 - coverage) * 255).astype(np.uint8)).save(pgm)
    subprocess.run(["potrace", pgm, "-s", "-o", svg, "--turdsize", "20", "--alphamax", "1.0",
                    "--opttolerance", "0.2", "-k", "0.5"], check=True)
    return open(svg).read()


def subpaths(svg, size):
    """Absolute cubic subpaths in unit coordinates (potrace writes relative commands in a
    translate(0,H) scale(0.1,-0.1) group)."""
    data = " ".join(re.findall(r'd="([^"]+)"', svg))
    tokens = re.findall(r"[MmCcLlZz]|-?\d+(?:\.\d+)?", data)
    result, current, x, y, start, i, cmd = [], None, 0.0, 0.0, (0.0, 0.0), 0, None

    def unit(px, py):
        return (px * 0.1 / size, (size - py * 0.1) / size)

    while i < len(tokens):
        t = tokens[i]
        if re.fullmatch(r"[A-Za-z]", t):
            cmd = t
            i += 1
            if cmd in "Zz":
                if current:
                    current.append(("Z",))
                    result.append(current)
                    current = None
                x, y = start
            continue
        if cmd in "Mm":
            nx, ny = float(tokens[i]), float(tokens[i + 1])
            i += 2
            if cmd == "m":
                nx, ny = x + nx, y + ny
            x, y = nx, ny
            start = (x, y)
            if current:
                result.append(current)
            current = [("M", unit(x, y))]
            cmd = "l" if cmd == "m" else "L"
        elif cmd in "Cc":
            vals = [float(v) for v in tokens[i : i + 6]]
            i += 6
            if cmd == "c":
                vals = [vals[0] + x, vals[1] + y, vals[2] + x, vals[3] + y, vals[4] + x, vals[5] + y]
            current.append(("C", unit(vals[0], vals[1]), unit(vals[2], vals[3]), unit(vals[4], vals[5])))
            x, y = vals[4], vals[5]
        elif cmd in "Ll":
            nx, ny = float(tokens[i]), float(tokens[i + 1])
            i += 2
            if cmd == "l":
                nx, ny = x + nx, y + ny
            x, y = nx, ny
            current.append(("L", unit(x, y)))
    if current:
        result.append(current)
    return result


def bbox(sub):
    pts = [p for seg in sub for p in seg[1:]]
    xs, ys = [p[0] for p in pts], [p[1] for p in pts]
    return min(xs), min(ys), max(xs), max(ys)


def swift(subs):
    lines = []
    for sub in subs:
        for seg in sub:
            if seg[0] == "M":
                lines.append(f"        p.move(to: pt({seg[1][0]:.5f}, {seg[1][1]:.5f}))")
            elif seg[0] == "L":
                lines.append(f"        p.addLine(to: pt({seg[1][0]:.5f}, {seg[1][1]:.5f}))")
            elif seg[0] == "C":
                (a, b), (c, d), (e, f) = seg[1], seg[2], seg[3]
                lines.append(f"        p.addCurve(to: pt({e:.5f}, {f:.5f}), control1: pt({a:.5f}, {b:.5f}), control2: pt({c:.5f}, {d:.5f}))")
            elif seg[0] == "Z":
                lines.append("        p.closeSubpath()")
    return "\n".join(lines)


def main():
    master, out = sys.argv[1], sys.argv[2]
    size, cover = masks(master)
    with tempfile.TemporaryDirectory() as tmp:
        coral = subpaths(trace(cover["coral"], tmp), size)
        cream = subpaths(trace(cover["cream"], tmp), size)
    # The sparkle is the small closed shape centred inside the card frame.
    def is_sparkle(sub):
        x0, y0, x1, y1 = bbox(sub)
        cx, cy, w = (x0 + x1) / 2, (y0 + y1) / 2, x1 - x0
        return abs(cx - 0.5) < 0.06 and 0.2 < cy < 0.5 and 0.08 < w < 0.25
    sparkle = [s for s in coral if is_sparkle(s)]
    frame = [s for s in coral if not is_sparkle(s)]
    assert len(sparkle) == 1, [bbox(s) for s in coral]
    sx0, sy0, sx1, sy1 = bbox(sparkle[0])
    header = f"""// Generated by scripts/brand/trace_logo.py from design/brand/icon-master-2026-09-23.png.
// Do not edit by hand; rerun the script if the logo changes.
import SwiftUI

/// MagicMobile's mark in unit coordinates (0…1 across the full-bleed icon).
enum BrandMarkPaths {{
    /// Center of the four-point sparkle, for glints and glows.
    static let sparkleCenter = CGPoint(x: {(sx0 + sx1) / 2:.5f}, y: {(sy0 + sy1) / 2:.5f})
    static let sparkleSize = CGSize(width: {sx1 - sx0:.5f}, height: {sy1 - sy0:.5f})
"""
    body = []
    for name, subs in [("cardFrame", frame), ("sparkle", sparkle), ("monogram", cream)]:
        body.append(f"""
    static func {name}(in rect: CGRect) -> Path {{
        func pt(_ x: CGFloat, _ y: CGFloat) -> CGPoint {{ CGPoint(x: rect.minX + x * rect.width, y: rect.minY + y * rect.height) }}
        var p = Path()
{swift(subs)}
        return p
    }}
""")
    with open(out, "w") as f:
        f.write(header + "".join(body) + "}\n")
    print("frame parts", len(frame), "sparkle", 1, "monogram parts", len(cream))


if __name__ == "__main__":
    main()
