package io.magicmobile.android.core

fun autoYieldChecks() {
    var checks=0
    fun verify(value:Boolean){checks++;check(value){"Auto-yield assertion $checks failed"}}
    val viewer="11111111-1111-1111-1111-111111111111"
    val opponent="22222222-2222-2222-2222-222222222222"
    val prompt=Decision("priority-1",10,"SELECT",mapOf("selectMode" to "priority","manaPlayerId" to viewer),setOf("boolean"),false,null,null)
    val context=AutoYieldPolicy.Context("match","seat",viewer,viewer,1,"running",true,true,true,true,false,prompt)
    val policy=AutoYieldPolicy()
    verify(AutoYieldPolicy.canStart(context))
    verify(!AutoYieldPolicy.canStart(context.copy(emptyStack=false)))
    verify(!AutoYieldPolicy.canStart(context.copy(activePlayerId=opponent)))
    verify(!AutoYieldPolicy.canStart(context.copy(foreground=false)))
    verify(!AutoYieldPolicy.canStart(context.copy(resyncRequired=true)))
    verify(!AutoYieldPolicy.canStart(context.copy(selfAuthority=false)))
    verify(!AutoYieldPolicy.canStart(context.copy(prompt=null)))
    verify(!AutoYieldPolicy.canStart(context.copy(prompt=prompt.copy(submitted=true))))
    verify(!AutoYieldPolicy.canStart(context.copy(prompt=prompt.copy(kind="ASK"))))
    verify(!AutoYieldPolicy.canStart(context.copy(prompt=prompt.copy(payload=prompt.payload+("manaPlayerId" to opponent)))))
    verify(policy.start(context,1_000))
    verify(policy.evaluate(context,1_001) is AutoYieldPolicy.Step.Pass)
    policy.recordPass(prompt)
    verify(policy.evaluate(context,1_002)==AutoYieldPolicy.Step.Wait)
    verify(policy.evaluate(context.copy(prompt=prompt.copy(revision=11)),1_003)==AutoYieldPolicy.Step.Wait)
    verify(policy.evaluate(context.copy(prompt=prompt.copy(id="new-but-old-revision")),1_004)==AutoYieldPolicy.Step.Wait)
    verify(policy.evaluate(context.copy(prompt=prompt.copy(id="fresh",revision=11)),1_005) is AutoYieldPolicy.Step.Pass)
    verify(policy.evaluate(context.copy(emptyStack=false),1_006)==AutoYieldPolicy.Step.Stop(AutoYieldPolicy.StopReason.STACK))
    verify(!policy.active)
    fun stopFor(next:AutoYieldPolicy.Context,reason:AutoYieldPolicy.StopReason){check(policy.start(context,0));verify(policy.evaluate(next,1)==AutoYieldPolicy.Step.Stop(reason))}
    stopFor(context.copy(turn=2),AutoYieldPolicy.StopReason.TURN_CHANGED)
    stopFor(context.copy(activePlayerId=opponent),AutoYieldPolicy.StopReason.TURN_CHANGED)
    stopFor(context.copy(foreground=false),AutoYieldPolicy.StopReason.INTERRUPTED)
    stopFor(context.copy(resyncRequired=true),AutoYieldPolicy.StopReason.INTERRUPTED)
    stopFor(context.copy(matchId="other-match"),AutoYieldPolicy.StopReason.CONTROL_CHANGED)
    stopFor(context.copy(seatId="other-seat"),AutoYieldPolicy.StopReason.CONTROL_CHANGED)
    stopFor(context.copy(viewerId=opponent),AutoYieldPolicy.StopReason.CONTROL_CHANGED)
    stopFor(context.copy(selfAuthority=false),AutoYieldPolicy.StopReason.CONTROL_CHANGED)
    stopFor(context.copy(phase="ended"),AutoYieldPolicy.StopReason.UNAVAILABLE)
    stopFor(context.copy(prompt=prompt.copy(kind="PICK_TARGET")),AutoYieldPolicy.StopReason.DECISION)
    check(policy.start(context,0));verify(policy.evaluate(context,60_000)==AutoYieldPolicy.Step.Stop(AutoYieldPolicy.StopReason.LIMIT))
    check(policy.start(context,0));repeat(64){policy.recordPass(prompt.copy(id="p-$it",revision=it.toLong()))}
    verify(policy.evaluate(context.copy(prompt=prompt.copy(id="over-limit",revision=100)),1)==AutoYieldPolicy.Step.Stop(AutoYieldPolicy.StopReason.LIMIT))
    val waiting=context.copy(activePlayerId=opponent,prompt=null)
    verify(policy.start(waiting,0,AutoYieldPolicy.Mode.UNTIL_MY_TURN))
    verify(policy.evaluate(waiting,1)==AutoYieldPolicy.Step.Wait)
    verify(policy.evaluate(waiting.copy(activePlayerId=viewer,turn=2),2)==AutoYieldPolicy.Step.Stop(AutoYieldPolicy.StopReason.TURN_CHANGED))
    verify(policy.start(context.copy(emptyStack=false),0,AutoYieldPolicy.Mode.END_TURN_SKIPPING_RESPONSES))
    verify(policy.evaluate(context.copy(emptyStack=false),1) is AutoYieldPolicy.Step.Pass)
    policy.stop();verify(policy.evaluate(context,2)==AutoYieldPolicy.Step.Wait)

    val owner=mapOf("playerId" to viewer,"isHuman" to true,"hasPriority" to true,"timerActive" to true)
    val game=mapOf("myPlayerId" to viewer,"activePlayerId" to viewer,"turn" to 1,"stack" to emptyMap<String,Any>(),"players" to listOf(owner))
    val snapshot=mapOf("enginePlayerId" to viewer,"controlledPlayerViews" to emptyMap<String,Any>(),"gameView" to game)
    val poll=GamePoll("match","seat",10,"running",snapshot,prompt,false,emptyList(),null)
    verify(AutoYieldPolicy.Context.fromPoll(poll,true)?.let{AutoYieldPolicy.canStart(it)}==true)
    verify(AutoYieldPolicy.Context.fromPoll(poll.copy(snapshot=snapshot-"controlledPlayerViews"),true)==null)
    val missingTimerView=game+("players" to listOf(owner-"timerActive"))
    verify(AutoYieldPolicy.Context.fromPoll(poll.copy(snapshot=snapshot+("gameView" to missingTimerView)),true)==null)
    val controlled=poll.copy(snapshot=snapshot+("controlledPlayerViews" to mapOf(opponent to game)))
    verify(AutoYieldPolicy.Context.fromPoll(controlled,true)?.selfAuthority==false)
    val timerOffView=game+("players" to listOf(owner+("timerActive" to false)))
    val timerOff=poll.copy(snapshot=snapshot+("gameView" to timerOffView))
    verify(AutoYieldPolicy.Context.fromPoll(timerOff,true)?.selfAuthority==false)
    verify(AutoYieldPolicy.Context.fromPoll(poll.copy(failure=mapOf("message" to "Engine failure")),true)==null)
    println("PASS: $checks Android auto-yield policy assertions")
}

fun main()=autoYieldChecks()
